### ISSUE TITLE
missing information on how to convert OMX OTF files to fairSIMxml

### ISSUE THREAD

**Issue by carandraug** [fairSIM/fairSIM-documentation#1]
The documentation states on a footnote:

> OMX OTF files can be converted to our format with a small, additional plugin.

However, there is no more information where to find that plugin. I have searched on the source for fairSIM and couldn't find anything there. On fairsim.github.io there is a download link for the standard omx v4 otfs already converted but not a tool to convert from other existing ones.

**Comment by mueller-physics** [comment]
Thanks for the info! As our publication was accepted, everything was moved to github, but I forgot the OTF reader plugin. Its now available here:

https://github.com/fairSIM/SRSIM-misc-tools

We have also done some tests, comparing estimated and measured OTFs, and for 2D you will probably not get much improvement over the estimated OTF.

**Comment by carandraug** [comment]
> [...] I forgot the OTF reader plugin. Its now available here:
> 
> https://github.com/fairSIM/SRSIM-misc-tools

Thank you. On a side note, do you think makes sense to have it merged with the fairSIM ImageJ plugin?

> We have also done some tests, comparing estimated and measured OTFs, and for 2D you will probably not get much improvement over the estimated OTF.

Actually we were trying fairSIM today and couldn't figure out how to perform a 3D reconstruction at all. We only got back single slices. Or are you talking about 3D OTFs for 2D reconstructions?

Adding @iandobbie to CC.

**Comment by mueller-physics** [comment]
I've moved the 3D question (short answer: currently only single-slice, but we are working on full 3D) to a separate [issue](https://github.com/fairSIM/fairSIM/issues/3).

> On a side note, do you think makes sense to have it merged with the fairSIM ImageJ plugin?

Our plan is to implement our own OTF measurement tool, and ship that together with fairSIM. [Gustafsson 2008](http://dx.doi.org/10.1529/biophysj.107.120345) explains how to do it, we just need to implement and test it properly. It will be needed for home-built systems, and I also don't know if e.g. the Zeiss or Nikon OTFs are user-accessible at all.

With all of this, I however don't know yet what the community needs most: Faster reconstructions, full 3D, other filters, etc... I hope soon, with the code and publication out, some people might join these discussion and maybe even contribute to the development.
